name: Update Fund Data

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 工作日北京时间20:00
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python fund.py data update
